# Generated by Django 3.0.3 on 2020-02-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_auto_20200217_2152'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='departments.SelectedCourse', verbose_name='courses'),
        ),
    ]
