# Generated by Django 3.0.3 on 2020-03-10 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_created', to=settings.AUTH_USER_MODEL, verbose_name='created user'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='delete_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last status update'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_status_updated', to=settings.AUTH_USER_MODEL, verbose_name='status updated user'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='integration_code',
            field=models.CharField(default='-', max_length=255, verbose_name='integration code'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'hidden'), (2, 'published'), (3, 'deleted'), (4, 'archive')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('bea884ef-e01e-48db-bbf9-9da16dbcb8e8'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated user'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='version',
            field=models.IntegerField(default=1, verbose_name='version'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_created', to=settings.AUTH_USER_MODEL, verbose_name='created user'),
        ),
        migrations.AddField(
            model_name='student',
            name='creation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date'),
        ),
        migrations.AddField(
            model_name='student',
            name='delete_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last status update'),
        ),
        migrations.AddField(
            model_name='student',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_status_updated', to=settings.AUTH_USER_MODEL, verbose_name='status updated user'),
        ),
        migrations.AddField(
            model_name='student',
            name='integration_code',
            field=models.CharField(default='-', max_length=255, verbose_name='integration code'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'hidden'), (2, 'published'), (3, 'deleted'), (4, 'archive')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='student',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('bea884ef-e01e-48db-bbf9-9da16dbcb8e8'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_updated', to=settings.AUTH_USER_MODEL, verbose_name='updated user'),
        ),
        migrations.AddField(
            model_name='student',
            name='version',
            field=models.IntegerField(default=1, verbose_name='version'),
        ),
    ]
