# Generated by Django 3.0.3 on 2020-03-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200310_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='integration_code',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='version',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='delete_time',
        ),
        migrations.RemoveField(
            model_name='student',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='integration_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='version',
        ),
    ]
