# Generated by Django 3.0.3 on 2020-03-11 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200310_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='history'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='integration_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='integration code'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'hidden'), (2, 'published'), (3, 'deleted'), (4, 'archive')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('2310f234-e37e-4970-8997-709427c8aaf5'), editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='history'),
        ),
        migrations.AddField(
            model_name='student',
            name='integration_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='integration code'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'hidden'), (2, 'published'), (3, 'deleted'), (4, 'archive')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='student',
            name='unique_id',
            field=models.UUIDField(default=uuid.UUID('2310f234-e37e-4970-8997-709427c8aaf5'), editable=False, unique=True),
        ),
    ]
