# Generated by Django 3.0.3 on 2020-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200311_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='unique_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
