# Generated by Django 3.0.3 on 2020-03-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200311_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='unique_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
