# Generated by Django 3.0.3 on 2020-03-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20200313_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
