# Generated by Django 3.0.3 on 2020-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20200313_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='slug',
            field=models.CharField(blank=True, help_text="Used to build the category's URL.", max_length=255, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.CharField(blank=True, help_text="Used to build the category's URL.", max_length=255, verbose_name='slug'),
        ),
    ]
