# Generated by Django 3.0.3 on 2020-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20200318_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='version',
            field=models.IntegerField(blank=True, default=1, verbose_name='current version'),
        ),
        migrations.AddField(
            model_name='student',
            name='version',
            field=models.IntegerField(blank=True, default=1, verbose_name='current version'),
        ),
    ]
