# Generated by Django 3.0.3 on 2020-03-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20200318_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='history',
            new_name='text_history',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='history',
            new_name='text_history',
        ),
    ]
