# Generated by Django 3.0.3 on 2020-03-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20200318_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='text_history',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='text_history',
            new_name='history',
        ),
    ]
