# Generated by Django 3.0.3 on 2020-03-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20200320_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='version',
            field=models.IntegerField(blank=True, verbose_name='current version'),
        ),
        migrations.AlterField(
            model_name='student',
            name='version',
            field=models.IntegerField(blank=True, verbose_name='current version'),
        ),
    ]
