# Generated by Django 3.0.3 on 2020-03-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20200320_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(blank=True, help_text="Used to build the category's URL.", null=True, upload_to='uploads/image.jpg', verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, help_text="Used to build the category's URL.", null=True, upload_to='uploads/image.jpg', verbose_name='slug'),
        ),
    ]
