# Generated by Django 3.0.3 on 2020-02-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorexpertise',
            options={'verbose_name': 'Instructor Expertise', 'verbose_name_plural': 'Instructor Expertise'},
        ),
        migrations.AlterModelOptions(
            name='instructorworkday',
            options={'verbose_name': 'Instructor Work Day', 'verbose_name_plural': 'Instructor Work Days'},
        ),
    ]
