# Generated by Django 3.0.3 on 2020-02-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_departmentperiod_term'),
        ('instructors', '0002_auto_20200217_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorworkday',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.Term', verbose_name='term'),
            preserve_default=False,
        ),
    ]
