# Generated by Django 3.0.3 on 2020-03-05 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedcourse',
            name='instructors',
            field=models.ManyToManyField(to='staff.Instructor', verbose_name='instructors'),
        ),
        migrations.AddField(
            model_name='selectedcourse',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Term', verbose_name='term'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='department_periods',
            field=models.ManyToManyField(to='departments.DepartmentPeriod', verbose_name='department periods'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Room', verbose_name='room'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='selected_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.SelectedCourse', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='departmentperiod',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='department'),
        ),
        migrations.AddField(
            model_name='departmentperiod',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Term', verbose_name='term'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.Department', verbose_name='department'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('selected_course', 'room')},
        ),
    ]
