# Generated by Django 3.0.3 on 2020-02-17 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20200217_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedcourse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='term',
            name='short_title',
        ),
    ]
