# Generated by Django 3.0.3 on 2020-02-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_auto_20200217_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='department_period',
        ),
        migrations.AddField(
            model_name='schedule',
            name='department_periods',
            field=models.ManyToManyField(to='departments.DepartmentPeriod', verbose_name='department periods'),
        ),
    ]
